language: node_js

env:
  global:
    secure: M9jZQUD6Ly0JM1/DMqOG1pOzXbMSFAz1pDPzhqHOpA8PYSh9DwcJf8o+nZWyBZmcszzMbsPdTEd328MNG1PhJEK7SWxozRnD4QiXVNk8v9QKqRUrXZb6Px8LLyoEGqCFslp9UuGDJeqRghDSlNJPfcYgHfj+Wzq9pjGw1Jx5Oxfd0GFnvwT3gKscRYkTCykbh10TVCqXXRK+8FCQw1m5XpIqSSpkWYAyGNFxbtdJgIhB2z7D94U783D93HCXhFXarlOMAbkLieRd5y3g6zXF7iUCji/JniEDqesmCqTEbZAAJEW9OC6aCQda8kro9+JS1KXMGAEVzZmsOdKzn2renge/ICXdgqEhxxJsbYYcs14ytmKhkSjjeSuAghMA8lGUWHZbr+FSe0ijQdqBN+sBCKpwnJBSnPvlLJOI+CiqUf4S2C7SaJJu5eb6TtkuKvUTbGhPCw0AJsSHviOajlPrUriOcNk6SsumM7LOJui1F3cyPZXfw8bplheLHGFPb72AxF5PzYiyfkmE3YZDnIdbrlGJmyebBUa9Ikl34op5yRVsJODvqO+zqcw5FRC8+StTb+wov3Yvf+IP/M/49OxqV7JR1Yk4N0quF3j/PGGn4PQPnOTEzh+dnOGVg4EH6KCxyv+2Qx+TRPfOB4LWy6aJ57jLbvt6WhXnfVSpnuJ2QuQ=

node_js:
- '4'
- '6'

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    
sudo: false

before_install:
- CXX=g++-4.8
- $CXX --version
- if [ "$TRAVIS_NODE_VERSION" = "0.8" ]; then npm install -g npm@2.7.3; fi;

before_script:
- COMMIT_MESSAGE=$(git show -s --format=%B $TRAVIS_COMMIT | tr -d '\n')
- NODE_PRE_GYP_GITHUB_TOKEN=
- export PATH=./node_modules/.bin/:$PATH

script:
- if [[ ${COMMIT_MESSAGE} =~ "[travis publish binary]" ]]; then node-pre-gyp package && node-pre-gyp-github
  publish --release; fi;
